title: "Mohammad Reza Rahmani"
tagline: "Information Theory • High-dimensional Statistics • Quantum"
author: "M. R. Rahmani"
email: you@example.com
url: "https://username.github.io"
theme: minima
# اگر خواستی پوسته‌ی دیگر:
# remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - google_analytics
# ناوبری ساده
minima:
  social_links:
    - { platform: github,  user_url: "https://github.com/username" }
    - { platform: google_scholar, user_url: "https://scholar.google.com/..." }
